# https://github.com/toilavinhdev/.dotfiles/blob/master/tmux/.tmux.conf

# -- general ----------------------------------------------------------

# enable mouse
set -g mouse on
set -g set-clipboard on

# performance
set -g history-limit 100000
set -sg escape-time 0
set -g focus-events on

# window, pane ordering
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# -- key binding ------------------------------------------------------

# prefix key
# unbind C-b
set -g prefix C-b
bind C-b send-prefix

# reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded ~/.config/tmux/tmux.conf"

# system
bind : command-prompt
bind ? list-keys

# session
bind s choose-tree -s
bind d detach-client
bind $ command-prompt -I "#S" "rename-session '%%'"

# window
bind w choose-tree -w
bind c new-window
bind n next-window
bind p previous-window
unbind '"'
bind | split-window -h -c "#{pane_current_path}"
unbind %
bind - split-window -v -c "#{pane_current_path}"

# pane
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind -r z resize-pane -Z

# -- display ----------------------------------------------------------

# true color support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -gq allow-passthrough on

# status bar
set -g status on
set -g status-position bottom
set -g status-interval 5
set -g status-left "[#S] "
set -g status-right "#{?client_prefix,#[bg=blue#,fg=white#,bold] ^B #[default],}#{?pane_in_mode,#[bg=red#,fg=white#,bold] MODE #[default],}#{?window_zoomed_flag,#[bg=magenta#,fg=white#,bold] ZOOM #[default],} #H | %I:%M %p"
set -g status-right-length 100
set -g status-style "bg=green,fg=black"
set -g window-status-format "#I:#W "
set -g window-status-current-format "#I:#W*"
set -g window-status-separator " "

# layout styles
set -g message-style "bg=yellow,fg=black"
set -g pane-border-style "fg=default"
set -g pane-active-border-style "fg=green"

# menu
bind e display-menu -T "#[align=centre]🐈" -x C -y C \
  "shell"               s       "display-popup -E -w 80% -h 80% -d '#{pane_current_path}' 'zsh'" \
  "git"                 g       "display-popup -E -w 80% -h 80% -d '#{pane_current_path}' 'lazygit'" \
  "docker"              d       "display-popup -E -w 80% -h 80% -d '#{pane_current_path}' 'lazydocker'" \
  "tmux"                t       "display-popup -E -w 80% -h 80% 'vi ~/.config/tmux/tmux.conf'" \
  "exit"                q       ""

# -- plugins ----------------------------------------------------------

# git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'

# list of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# initialize tmux plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'