# ── Prefix Key
# Default prefix: Ctrl+b (no change needed)

# ── Reload key
bind r source-file ~/.tmux.conf \; display "TMUX CONFIG RELOADED"

# ── General Settings
set -g mouse on
set -g history-limit 100000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -sg escape-time 0
set -g focus-events on
set -g set-clipboard on

# ── Panes Settings
# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %
# move around panes with hjkl, as one would in vim after pressing 
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# resize the pane using Prefix H, J, K, L
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

# ── Status Bar
set -g status-position bottom
set -g status-interval 5